In [1]:
!pip install playwright pytest-playwright

Collecting playwright
  Downloading playwright-1.58.0-py3-none-win_amd64.whl (36.8 MB)
     --------------------------------------- 36.8/36.8 MB 26.2 MB/s eta 0:00:00
Collecting pytest-playwright
  Downloading pytest_playwright-0.7.2-py3-none-any.whl (16 kB)
Requirement already satisfied: greenlet<4.0.0,>=3.1.1 in c:\users\i.taldykin\appdata\local\programs\python\python310\lib\site-packages (from playwright) (3.2.4)
Collecting pyee<14,>=13
  Downloading pyee-13.0.1-py3-none-any.whl (15 kB)
Collecting pytest<10.0.0,>=6.2.4
  Downloading pytest-9.0.2-py3-none-any.whl (374 kB)
     ------------------------------------- 374.8/374.8 kB 22.8 MB/s eta 0:00:00
Collecting python-slugify<9.0.0,>=6.0.0
  Downloading python_slugify-8.0.4-py2.py3-none-any.whl (10 kB)
Collecting pytest-base-url<3.0.0,>=1.0.0
  Downloading pytest_base_url-2.1.0-py3-none-any.whl (5.3 kB)
Requirement already satisfied: typing-extensions in c:\users\i.taldykin\appdata\local\programs\python\python310\lib\site-packages (from pyee<14,>=13->playwright) (4.14.1)
Requirement already satisfied: colorama>=0.4 in c:\users\i.taldykin\appdata\roaming\python\python310\site-packages (from pytest<10.0.0,>=6.2.4->pytest-playwright) (0.4.6)
Requirement already satisfied: exceptiongroup>=1 in c:\users\i.taldykin\appdata\roaming\python\python310\site-packages (from pytest<10.0.0,>=6.2.4->pytest-playwright) (1.3.0)
Collecting pluggy<2,>=1.5
  Downloading pluggy-1.6.0-py3-none-any.whl (20 kB)
Requirement already satisfied: packaging>=22 in c:\users\i.taldykin\appdata\roaming\python\python310\site-packages (from pytest<10.0.0,>=6.2.4->pytest-playwright) (25.0)
Collecting tomli>=1
  Downloading tomli-2.4.1-py3-none-any.whl (14 kB)
Collecting iniconfig>=1.0.1
  Downloading iniconfig-2.3.0-py3-none-any.whl (7.5 kB)
Requirement already satisfied: pygments>=2.7.2 in c:\users\i.taldykin\appdata\roaming\python\python310\site-packages (from pytest<10.0.0,>=6.2.4->pytest-playwright) (2.19.2)
Requirement already satisfied: requests>=2.9 in c:\users\i.taldykin\appdata\local\programs\python\python310\lib\site-packages (from pytest-base-url<3.0.0,>=1.0.0->pytest-playwright) (2.32.5)
Collecting text-unidecode>=1.3
  Downloading text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
     ---------------------------------------- 78.2/78.2 kB 4.2 MB/s eta 0:00:00
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\i.taldykin\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.9->pytest-base-url<3.0.0,>=1.0.0->pytest-playwright) (2.5.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\i.taldykin\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.9->pytest-base-url<3.0.0,>=1.0.0->pytest-playwright) (3.11)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\i.taldykin\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.9->pytest-base-url<3.0.0,>=1.0.0->pytest-playwright) (3.4.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\i.taldykin\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.9->pytest-base-url<3.0.0,>=1.0.0->pytest-playwright) (2025.10.5)
Installing collected packages: text-unidecode, tomli, python-slugify, pyee, pluggy, iniconfig, pytest, playwright, pytest-base-url, pytest-playwright
Successfully installed iniconfig-2.3.0 playwright-1.58.0 pluggy-1.6.0 pyee-13.0.1 pytest-9.0.2 pytest-base-url-2.1.0 pytest-playwright-0.7.2 python-slugify-8.0.4 text-unidecode-1.3 tomli-2.4.1

[notice] A new release of pip available: 22.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import os
import pandas as pd
from sqlalchemy import create_engine
import pyodbc
import win32com.client as win32
import time  # Для измерения времени выполнения
import shutil
import re
# import pyarrow as pa
# import pyarrow.csv as csv


FOLDER_PATH = os.path.normpath(r"\\kari.local\public\all\Analytics\Marketplaceanalytics\Федоров\Дашбоард по рекламным кампаниям\!!!_ИСХОДНИКИ ДЛЯ ДАШБОРДА_НЕ УДАЛЯТЬ_!!!")
# Сохранение финальной таблицы
df = pd.read_csv(os.path.join(FOLDER_PATH, "ДБсПризнаками_Ozon.csv"))
# df = pd.read_csv(os.path.join(FOLDER_PATH, "ДБсПризнаками.csv"))
# print(df.head(20))
# print(df.columns)

C:\Users\i.taldykin\AppData\Local\Temp\ipykernel_10612\3341566417.py:15: DtypeWarning: Columns (121,122,124,125) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(FOLDER_PATH, "ДБсПризнаками_Ozon.csv"))

In [6]:
print(list(df.columns))

['Дата', 'Артикул', 'Артикул OZ', 'ТипАктивности', 'Наименование', 'Коллекция', 'Бренд', 'Сезон', 'Направление', 'Розничный отдел', 'Модель', 'Группа', 'Бизнес-группа', 'Техсегмент', 'Байер', 'Две последние коллекции', 'Основной артикул', 'Себестоимость с НДС', 'Процент выкупа', 'НДС', 'Ответственный за группу', 'Группа для отчетов', 'SKU из объединенной карточки', 'Ассоциированные заказы, руб', 'Ассоциированные заказы, шт', 'Вывод в топ', 'Трафарет', 'Оплата за заказ', 'Органика', 'Вывод в топ_Показы, всего', 'Трафарет_Показы, всего', 'Оплата за заказ_Показы, всего', 'Органика_Показы, всего', 'Вывод в топ_Показы на карточке товара', 'Трафарет_Показы на карточке товара', 'Оплата за заказ_Показы на карточке товара', 'Органика_Показы на карточке товара', 'Вывод в топ_Показы в поиске и каталоге', 'Трафарет_Показы в поиске и каталоге', 'Оплата за заказ_Показы в поиске и каталоге', 'Органика_Показы в поиске и каталоге', 'Вывод в топ_Позиция в поиске и каталоге', 'Трафарет_Позиция в поиске и каталоге', 'Оплата за заказ_Позиция в поиске и каталоге', 'Органика_Позиция в поиске и каталоге', 'Вывод в топ_В корзину, всего', 'Трафарет_В корзину, всего', 'Оплата за заказ_В корзину, всего', 'Органика_В корзину, всего', 'Вывод в топ_Заказано товаров', 'Трафарет_Заказано товаров', 'Оплата за заказ_Заказано товаров', 'Органика_Заказано товаров', 'Вывод в топ_Отменено товаров', 'Трафарет_Отменено товаров', 'Оплата за заказ_Отменено товаров', 'Органика_Отменено товаров', 'Вывод в топ_Доставлено товаров', 'Трафарет_Доставлено товаров', 'Оплата за заказ_Доставлено товаров', 'Органика_Доставлено товаров', 'Вывод в топ_Возвращено товаров', 'Трафарет_Возвращено товаров', 'Оплата за заказ_Возвращено товаров', 'Органика_Возвращено товаров', 'Вывод в топ_Заказано на сумму', 'Трафарет_Заказано на сумму', 'Оплата за заказ_Заказано на сумму', 'Органика_Заказано на сумму', 'Вывод в топ_В корзину из карточки товара', 'Трафарет_В корзину из карточки товара', 'Оплата за заказ_В корзину из карточки товара', 'Органика_В корзину из карточки товара', 'Вывод в топ_Выкупили ШТ', 'Трафарет_Выкупили ШТ', 'Оплата за заказ_Выкупили ШТ', 'Органика_Выкупили ШТ', 'Вывод в топ_Расход, ₽', 'Трафарет_Расход, ₽', 'Оплата за заказ_Расход, ₽', 'Органика_Расход, ₽', 'Вывод в топ_Рекламные заказано на сумму', 'Трафарет_Рекламные заказано на сумму', 'Оплата за заказ_Рекламные заказано на сумму', 'Органика_Рекламные заказано на сумму', 'Вывод в топ_Рекламные заказано товаров', 'Трафарет_Рекламные заказано товаров', 'Оплата за заказ_Рекламные заказано товаров', 'Органика_Рекламные заказано товаров', 'Вывод в топ_Рекламные показы', 'Трафарет_Рекламные показы', 'Оплата за заказ_Рекламные показы', 'Органика_Рекламные показы', 'Вывод в топ_Рекламные показы на карточке товара', 'Трафарет_Рекламные показы на карточке товара', 'Оплата за заказ_Рекламные показы на карточке товара', 'Органика_Рекламные показы на карточке товара', 'Вывод в топ_Цена', 'Трафарет_Цена', 'Оплата за заказ_Цена', 'Органика_Цена', 'Показы, всего', 'Показы на карточке товара', 'Показы в поиске и каталоге', 'Позиция в поиске и каталоге', 'В корзину, всего', 'Заказано товаров', 'Отменено товаров', 'Доставлено товаров', 'Возвращено товаров', 'Заказано на сумму', 'В корзину из карточки товара', 'Выкупили ШТ', 'Расход, ₽', 'Рекламные заказано на сумму', 'Рекламные заказано товаров', 'Рекламные показы', 'Рекламные показы на карточке товара', 'Цена', 'Остаток Агрегатора', 'Дистрибуция', 'Признак Артикула 1', 'Признак Артикула 2', 'Признак Артикула 3', 'Признак Артикула 4', 'Признак Артикула 5', 'Признак Даты 1', 'Признак Даты 2', 'Признак Даты 3', 'Признак Даты 4', 'Признак Даты 5', 'Текущая склейка']

In [3]:
df['ТипАктивности'].value_counts()

KeyError: 'ТипАктивности'

In [4]:
df['Цена'].unique()

array([ 1298.,  2199.,  1445., ...,  7644.,  9610., 10624.],
      shape=(12062,))

In [ ]:
df['Дата'].unique()

array(['2025-12-15', '2025-12-16', '2025-12-17', '2025-12-18',
       '2025-12-19', '2025-12-20', '2025-12-21', '2025-12-22',
       '2025-12-23', '2025-12-24', '2025-12-25', '2025-12-26',
       '2025-12-27', '2025-12-28', '2025-12-29', '2025-12-30',
       '2025-12-31', '2026-01-01', '2026-01-02', '2026-01-03',
       '2026-01-04', '2026-01-05', '2026-01-06', '2026-01-07',
       '2026-01-08', '2026-01-09', '2026-01-10', '2026-01-11',
       '2026-01-12', '2026-01-13', '2026-01-14', '2026-01-15',
       '2026-01-16', '2026-01-17', '2026-01-18', '2026-01-19',
       '2026-01-20', '2026-01-21', '2026-01-22', '2026-01-23',
       '2026-01-24', '2026-01-25', '2026-01-26', '2026-01-27',
       '2026-01-28', '2026-01-29', '2026-01-30', '2026-01-31',
       '2026-02-01', '2026-02-02', '2026-02-03', '2026-02-04',
       '2026-02-05', '2026-02-06', '2026-02-07', '2026-02-08',
       '2026-02-09', '2026-02-10'], dtype=object)

In [5]:
df

,Дата,Артикул,Артикул OZ,Наименование,Коллекция,Бренд,Сезон,Направление,Розничный отдел,Модель,...,Признак Артикула 2,Признак Артикула 3,Признак Артикула 4,Признак Артикула 5,Признак Даты 1,Признак Даты 2,Признак Даты 3,Признак Даты 4,Признак Даты 5,ТипАктивности
0,2025-09-01,00006020,1.493938e+08,Балетки женские 298-9CK,2019SS,T.TACCARDI,лето (закрытое),Женская обувь,Женская обувь,298-9CK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Органика
1,2025-09-01,00006050,1.493909e+08,Балетки женские ZS1810-1K,2019SS,T.TACCARDI,лето (закрытое),Женская обувь,Женская обувь,ZS1810-1K,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Органика
2,2025-09-01,00006060,1.493910e+08,Балетки женские ZS183-2K,2019SS,T.TACCARDI,лето (закрытое),Женская обувь,Женская обувь,ZS183-2K,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Органика
3,2025-09-01,00006080,1.493909e+08,Балетки женские ZS189-7K,2019SS,T.TACCARDI,лето (закрытое),Женская обувь,Женская обувь,ZS189-7K,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Органика
4,2025-09-01,000060H0,1.493724e+08,Балетки женские K0346PM-1A,2019SS,PIERRE CARDIN,лето (закрытое),Женская обувь,Женская обувь,K0346PM-1A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Органика
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3797039,2025-11-16,y9808110,1.997932e+09,Шорты мужские A85512-2,2025SS,kari,всесезонный,Одежда для мужчин,Спортивная одежда для мужчин,A85512-2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Органика
3797040,2025-11-16,y9808120,1.997933e+09,Шорты мужские A85512-3,2025SS,kari,всесезонный,Одежда для мужчин,Спортивная одежда для мужчин,A85512-3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Органика
3797041,2025-11-16,y9808130,1.934644e+09,Шорты мужские SS25C2020,2025SS,kari,"весна, лето",Одежда для мужчин,"Брюки, шорты мужские",SS25C2020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Органика
3797042,2025-11-16,y9808140,1.950209e+09,Шорты мужские SS25C2021,2025SS,kari,"весна, лето",Одежда для мужчин,"Брюки, шорты мужские",SS25C2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Органика
3797043,2025-11-16,y9808150,1.950209e+09,Шорты мужские SS25C2022,2025SS,kari,"весна, лето",Одежда для мужчин,"Брюки, шорты мужские",SS25C2022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Органика

In [8]:
# --- фильтрация по нужным датам ---
dates = ['23.10.2025', '22.10.2025', '21.10.2025', '20.10.2025']
df_filtered = df[df['Дата'].isin(dates)]

# --- группировка и агрегация ---
df_result = (
    df_filtered
    .groupby('Дата', as_index=False)
    .agg({
        'КолвоЗаказанных_распред': 'sum',
        'СуммаЗаказов_распред': 'sum'
    })
    .rename(columns={
        'КолвоЗаказанных_распред': 'CountOrdered',
        'СуммаЗаказов_распред': 'SummaryOrdered'
    })
)

print(df_result)

         Дата  CountOrdered  SummaryOrdered
0  20.10.2025         59070     157828105.0
1  21.10.2025         52311     137851207.0
2  22.10.2025         56212     145360919.0
3  23.10.2025         36014      91923647.0

In [2]:
df[df['Дата']=="2025-10-22"]

Empty DataFrame
Columns: [Дата, Артикул WB, Рейтинг карточки, Показы, Показы на карточке товара, Положили в корзину, Заказали, шт, Выкупили, шт, Отменили, шт, Заказали на сумму, руб, Выкупили на сумму, руб, Отменили на сумму, руб, Средняя цена, руб, Рейтинг по отзывам, Артикул, Наименование, Коллекция, Бренд, Сезон, Направление, Розничный отдел, Модель, Группа, Бизнес-группа, Техсегмент, Байер, Две последние коллекции, Основной артикул, Себестоимость с НДС, Процент выкупа ВБ, НДС, Ответственный за группу, Группа для отчетов, Тип активности, Автоматическое_ID кампании, Автоматическое_Расход, руб, Автоматическое_Рекламные Заказы, шт, Автоматическое_Рекламные в корзину, Автоматическое_Рекламные заказаных товаров, шт, Автоматическое_Рекламные заказов на сумму, Автоматическое_Рекламные клики, Автоматическое_Рекламные показы, Аукцион_ID кампании, Аукцион_Расход, руб, Аукцион_Рекламные Заказы, шт, Аукцион_Рекламные в корзину, Аукцион_Рекламные заказаных товаров, шт, Аукцион_Рекламные заказов на сумму, Аукцион_Рекламные клики, Аукцион_Рекламные показы, Рекламные показы, Рекламные заказов на сумму, Рекламные Заказы, шт, Рекламные клики, Рекламные в корзину, Рекламные заказаных товаров, шт, Расход, руб, Автоматическое, Аукцион, Цена, Остаток Агрегатора, Дистрибуция, Показы из выгрузки, Клики из выгрузки, Корзины из выгрузки, Заказы из выгрузки, Признак Артикула 1, Признак Артикула 2, Признак Артикула 3, Признак Артикула 4, Признак Артикула 5, Признак Даты 1, Признак Даты 2, Признак Даты 3, Признак Даты 4, Признак Даты 5, Текущая склейка]
Index: []

[0 rows x 77 columns]

In [2]:
print(list(df.columns))

['Дата', 'Артикул', 'Артикул OZ', 'Наименование', 'Коллекция', 'Бренд', 'Сезон', 'Направление', 'Розничный отдел', 'Модель', 'Группа', 'Бизнес-группа', 'Техсегмент', 'Байер', 'Две последние коллекции', 'Основной артикул', 'Себестоимость с НДС', 'Процент выкупа', 'НДС', 'Ответственный за группу', 'Группа для отчетов', 'ID кампании', 'Инструмент', 'Место размещения', 'Вывод в топ', 'Трафарет', 'Оплата за заказ', 'Органика', 'Вывод в топ_Показы, всего', 'Трафарет_Показы, всего', 'Оплата за заказ_Показы, всего', 'Органика_Показы, всего', 'Показы, всего', 'Вывод в топ_Показы на карточке товара', 'Трафарет_Показы на карточке товара', 'Оплата за заказ_Показы на карточке товара', 'Органика_Показы на карточке товара', 'Показы на карточке товара', 'Вывод в топ_Показы в поиске и каталоге', 'Трафарет_Показы в поиске и каталоге', 'Оплата за заказ_Показы в поиске и каталоге', 'Органика_Показы в поиске и каталоге', 'Показы в поиске и каталоге', 'Вывод в топ_Позиция в поиске и каталоге', 'Трафарет_Позиция в поиске и каталоге', 'Оплата за заказ_Позиция в поиске и каталоге', 'Органика_Позиция в поиске и каталоге', 'Позиция в поиске и каталоге', 'Вывод в топ_В корзину, всего', 'Трафарет_В корзину, всего', 'Оплата за заказ_В корзину, всего', 'Органика_В корзину, всего', 'В корзину, всего', 'Вывод в топ_Заказано товаров', 'Трафарет_Заказано товаров', 'Оплата за заказ_Заказано товаров', 'Органика_Заказано товаров', 'Заказано товаров', 'Вывод в топ_Отменено товаров', 'Трафарет_Отменено товаров', 'Оплата за заказ_Отменено товаров', 'Органика_Отменено товаров', 'Отменено товаров', 'Вывод в топ_Доставлено товаров', 'Трафарет_Доставлено товаров', 'Оплата за заказ_Доставлено товаров', 'Органика_Доставлено товаров', 'Доставлено товаров', 'Вывод в топ_Возвращено товаров', 'Трафарет_Возвращено товаров', 'Оплата за заказ_Возвращено товаров', 'Органика_Возвращено товаров', 'Возвращено товаров', 'Вывод в топ_Заказано на сумму', 'Трафарет_Заказано на сумму', 'Оплата за заказ_Заказано на сумму', 'Органика_Заказано на сумму', 'Заказано на сумму', 'Вывод в топ_В корзину из карточки товара', 'Трафарет_В корзину из карточки товара', 'Оплата за заказ_В корзину из карточки товара', 'Органика_В корзину из карточки товара', 'В корзину из карточки товара', 'Вывод в топ_Выкупили ШТ', 'Трафарет_Выкупили ШТ', 'Оплата за заказ_Выкупили ШТ', 'Органика_Выкупили ШТ', 'Выкупили ШТ', 'Вывод в топ_Расход, ₽', 'Трафарет_Расход, ₽', 'Оплата за заказ_Расход, ₽', 'Органика_Расход, ₽', 'Расход, ₽', 'Вывод в топ_Рекламные заказано на сумму', 'Трафарет_Рекламные заказано на сумму', 'Оплата за заказ_Рекламные заказано на сумму', 'Органика_Рекламные заказано на сумму', 'Рекламные заказано на сумму', 'Вывод в топ_Рекламные заказано товаров', 'Трафарет_Рекламные заказано товаров', 'Оплата за заказ_Рекламные заказано товаров', 'Органика_Рекламные заказано товаров', 'Рекламные заказано товаров', 'Вывод в топ_Рекламные показы', 'Трафарет_Рекламные показы', 'Оплата за заказ_Рекламные показы', 'Органика_Рекламные показы', 'Рекламные показы', 'Вывод в топ_Рекламные показы на карточке товара', 'Трафарет_Рекламные показы на карточке товара', 'Оплата за заказ_Рекламные показы на карточке товара', 'Органика_Рекламные показы на карточке товара', 'Рекламные показы на карточке товара', 'Вывод в топ_Цена', 'Трафарет_Цена', 'Оплата за заказ_Цена', 'Органика_Цена', 'Цена', 'Остаток Агрегатора', 'Дистрибуция', 'Признак Артикула 1', 'Признак Артикула 2', 'Признак Артикула 3', 'Признак Артикула 4', 'Признак Артикула 5', 'Признак Даты 1', 'Признак Даты 2', 'Признак Даты 3', 'Признак Даты 4', 'Признак Даты 5', 'ТипАктивности', 'Текущая склейка']

In [4]:
# Органика
mask = (
    ((df['Расход, ₽'] == 0) | 
     (df['Расход, ₽'] == 0.0))
)
df.loc[mask, 'ТипАктивности'] = 'Органика'

In [3]:
df[((df['Расход, ₽'] == 0) & (df['ТипАктивности'] == "Трафарет"))][['Артикул', "Дата", "Артикул OZ", "ТипАктивности", "Инструмент","Расход, ₽"]]

Empty DataFrame
Columns: [Артикул, Дата, Артикул OZ, ТипАктивности, Инструмент, Расход, ₽]
Index: []

In [5]:
# Сохранение финальной таблицы
df.to_csv(os.path.join(FOLDER_PATH, "ДБсПризнаками_Ozon.csv"), index=False)